### ISSUE TITLE
nuget 包不可用

### ISSUE THREAD

**Issue by SimTsai** [stulzq/RSAUtil#1]

**Comment by stulzq** [comment]
请贴出错误截图，如果是下载失败，那么请检查网络或者切换包源

**Comment by SimTsai** [comment]
```shell
dotnet add package XC.Framework.Security.RSAUtil --version 1.0.0
```

>>>
Writing tmpC40F.tmp
info : Adding PackageReference for package 'XC.Framework.Security.RSAUtil' into project '.csproj'.
log  : Restoring packages for .csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/bouncycastle.crypto/index.json
error: Unable to find a stable package BouncyCastle.Crypto with version (>= 1.0.0)
error:   - Found 1 version(s) in NuGet [ Nearest version: 1.8.0-beta4 ]
error: Package 'XC.Framework.Security.RSAUtil' is incompatible with 'all' frameworks in project '.csproj'.
>>>

**Comment by SimTsai** [comment]
![issue 1](https://user-images.githubusercontent.com/13759975/36822524-718625e4-1d33-11e8-83f9-e368de738108.png)

**Comment by stulzq** [comment]
谢谢你提出这个问题 今晚我修复下

**Comment by stulzq** [comment]
已解决 请使用1.0.1版本
