### ISSUE TITLE
RsaKeyGenerator class Replace("\r\n", "")  bug in linux 

### ISSUE THREAD

**Issue by youngMvcBrother** [stulzq/RSAUtil#13]
linux ‘\r\n’ is ‘\n‘

**Comment by youngMvcBrother** [comment]
> [``](

- 

- [ ] 1. url

)

**Comment by stulzq** [comment]
With your close and reopen, I also closed and reopened vs2019

**Comment by youngMvcBrother** [comment]
I'm sorry;
    Misoperation;
        Just now the network is unstable!




------------------ 原始邮件 ------------------
发件人: "Zhiqiang Li"<notifications@github.com>; 
发送时间: 2019年9月20日(星期五) 下午2:31
收件人: "stulzq/RSAUtil"<RSAUtil@noreply.github.com>; 
抄送: "枪已上膛"<949827573@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [stulzq/RSAUtil] RsaKeyGenerator class Replace("\r\n", "")  bugin linux  (#13)




With your close and reopen, I also closed and reopened vs2019
